const VERB_DICTIONARY = [
  { root: "كتب", ru: "писать", presentVowel: "u" },
  { root: "فتح", ru: "открывать", presentVowel: "a" },
  { root: "ذهب", ru: "идти", presentVowel: "a" },
  { root: "درس", ru: "учить", presentVowel: "u" },
  { root: "دخل", ru: "входить", presentVowel: "u" },
  { root: "خرج", ru: "выходить", presentVowel: "u" },
  { root: "جلس", ru: "сидеть", presentVowel: "i" },
  { root: "شرب", ru: "пить", presentVowel: "a" },
  { root: "سمع", ru: "слышать", presentVowel: "a" },
  { root: "علم", ru: "знать", presentVowel: "a" },
  { root: "لعب", ru: "играть", presentVowel: "a" },
  { root: "سكن", ru: "жить", presentVowel: "u" },
  { root: "فهم", ru: "понимать", presentVowel: "a" },
  { root: "حفظ", ru: "запоминать", presentVowel: "a" },
  { root: "طلب", ru: "просить", presentVowel: "u" },
  { root: "نصر", ru: "помогать", presentVowel: "u" },
  { root: "ضرب", ru: "бить", presentVowel: "i" },
  { root: "غسل", ru: "мыть", presentVowel: "i" },
  { root: "طبخ", ru: "готовить", presentVowel: "u" },
  { root: "رسم", ru: "рисовать", presentVowel: "u" },
  { root: "لبس", ru: "надевать", presentVowel: "a" },
  { root: "حمل", ru: "нести", presentVowel: "i" },
  { root: "وجد", ru: "находить", presentVowel: "i" },
  { root: "عبد", ru: "поклоняться", presentVowel: "u" },
  { root: "سجد", ru: "падать ниц", presentVowel: "u" },
  { root: "ركع", ru: "кланяться", presentVowel: "a" },
  { root: "جمع", ru: "собирать", presentVowel: "a" },
  { root: "رفع", ru: "поднимать", presentVowel: "a" },
  { root: "نزل", ru: "спускаться", presentVowel: "i" },
  { root: "صعد", ru: "подниматься", presentVowel: "a" },
  { root: "سأل", ru: "спрашивать", presentVowel: "a" },
  { root: "منع", ru: "запрещать", presentVowel: "a" },
  { root: "قصد", ru: "намереваться", presentVowel: "i" },
  { root: "قبل", ru: "принимать", presentVowel: "a" },
  { root: "رفض", ru: "отказываться", presentVowel: "u" },
  { root: "حضر", ru: "присутствовать", presentVowel: "u" },
  { root: "غفر", ru: "прощать", presentVowel: "i" },
  { root: "رحم", ru: "миловать", presentVowel: "a" },
  { root: "خلق", ru: "создавать", presentVowel: "u" },
  { root: "رزق", ru: "наделять", presentVowel: "u" },
  { root: "ملك", ru: "владеть", presentVowel: "i" },
  { root: "حكم", ru: "судить", presentVowel: "u" },
  { root: "قتل", ru: "убивать", presentVowel: "u" },
  { root: "كسب", ru: "зарабатывать", presentVowel: "i" },
  { root: "عمل", ru: "работать", presentVowel: "a" },
  { root: "شكر", ru: "благодарить", presentVowel: "u" },
  { root: "ذكر", ru: "поминать", presentVowel: "u" },
  { root: "صبر", ru: "терпеть", presentVowel: "i" },
  { root: "صدق", ru: "быть правдивым", presentVowel: "u" },
  { root: "كذب", ru: "лгать", presentVowel: "i" },

  { root: "قرأ", ru: "читать", presentVowel: "a" },
  { root: "أكل", ru: "есть", presentVowel: "u" },
  { root: "قام", ru: "вставать", presentVowel: "u" },
  { root: "نام", ru: "спать", presentVowel: "a" },
  { root: "مشى", ru: "идти пешком", presentVowel: "i" },
  { root: "رجع", ru: "возвращаться", presentVowel: "i" },
  { root: "وصل", ru: "прибывать", presentVowel: "i" },
  { root: "بدأ", ru: "начинать", presentVowel: "a" },
  { root: "انتهى", ru: "заканчивать", presentVowel: "i" },
  { root: "عرف", ru: "знать", presentVowel: "i" },
  { root: "كره", ru: "ненавидеть", presentVowel: "a" },
  { root: "حب", ru: "любить", presentVowel: "u" },
  { root: "ساعد", ru: "помогать", presentVowel: "u" },
  { root: "دفع", ru: "платить", presentVowel: "a" },
  { root: "أغلق", ru: "закрывать", presentVowel: "i" },
  { root: "ركب", ru: "садиться", presentVowel: "a" },
  { root: "وقف", ru: "останавливаться", presentVowel: "i" },
  { root: "سافر", ru: "путешествовать", presentVowel: "i" },
  { root: "طار", ru: "летать", presentVowel: "i" },
  { root: "سبح", ru: "плавать", presentVowel: "a" },
  { root: "ضحك", ru: "смеяться", presentVowel: "a" },
  { root: "بكى", ru: "плакать", presentVowel: "i" },
  { root: "سمح", ru: "разрешать", presentVowel: "a" },
  { root: "شرح", ru: "объяснять", presentVowel: "a" }, 
  { root: "استعمل", ru: "использовать", presentVowel: "i" },
  { root: "تعلّم", ru: "учиться", presentVowel: "a" },
  { root: "درّس", ru: "преподавать", presentVowel: "u" },
  { root: "اشتغل", ru: "работать", presentVowel: "a" },

  { root: "قال", ru: "говорить", irregular: "qala" },
  { root: "باع", ru: "продавать", irregular: "baa" },
  { root: "جاء", ru: "приходить", irregular: "jaa" },
  { root: "رأى", ru: "видеть", irregular: "raa" },
  { root: "دعا", ru: "звать / молиться", irregular: "daa" }
];